imports:
  - php

before_commands:
  - composer install

tools:
  php_code_sniffer:
    filter:
      excluded-paths: [ spec/*, integration/*, features/* ]
    config:
      standard: PSR2

  php_analyzer:
    filter:
      excluded-paths: [ spec/*, integration/* ]

  php_sim:
    filter:
      excluded-paths: [ spec/*, integration/* ]

  php_cpd:
    enabled: true
    excluded_dirs: [ spec/*, integration/* ]

  php_cs_fixer:
    enabled: true
    config:
      level: all

  php_loc:
    enabled: true
    excluded_dirs: [ spec/*, integration/* ]

  php_mess_detector:
    enabled: true

  php_pdepend:
    enabled: true
    excluded_dirs: [ spec/*, integration/* ]

  sensiolabs_security_checker:
      enabled: true

build_failure_conditions:
    - 'issues.label("coding-style").exists'

filter:
  excluded_paths:
    - specs/*
    - vendor/*
