language: php

sudo: true

addons:
  apt:
    packages:
      - php5-cli
      - php5-curl

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 5.3
      env: IGNORE_PHPENV='yes'
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: hhvm
  allow_failures:
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: hhvm

before_install:
  - composer selfupdate

install:
  - export COMPOSER_ROOT_VERSION=dev-master
  - composer update
  - sudo apt-get remove libcurl4-gnutls-dev
  - sudo apt-get install libcurl4-openssl-dev

script:
  - if [ "$IGNORE_PHPENV" == "yes" ]; then /usr/bin/php5 vendor/bin/phpspec run --format=pretty; fi;
  - if [ "$IGNORE_PHPENV" != "yes" ]; then php vendor/bin/phpspec run --format=pretty; fi;
