language: php

sudo: true

addons:
  apt:
    packages:
      - php5-cli
      - php5-curl

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
  allow_failures:
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1

before_install:
  - composer selfupdate

install:
  - export COMPOSER_ROOT_VERSION=dev-master
  - composer update
  - sudo apt-get remove libcurl4-gnutls-dev
  - sudo apt-get install libcurl4-openssl-dev

script:
  - php vendor/bin/phpspec run --format=pretty
