language: php

sudo: false

addons:
  apt:
    packages:
      - php5-cli
      - php5-curl

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 5.3
      env: IGNORE_PHPENV='yes'
    - php: hhvm
  allow_failures:
    - php: hhvm
  fast_finish: true

before_install:
  - composer selfupdate

install:
  - export COMPOSER_ROOT_VERSION=dev-master
  - composer update

script:
  - if [ "$IGNORE_PHPENV" == "yes" ]; then /usr/bin/php5 vendor/bin/phpspec run --format=pretty; fi;
  - if [ "$IGNORE_PHPENV" != "yes" ]; then php vendor/bin/phpspec run --format=pretty; fi;
