<?php

// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'authorize3d' => '/requests/transactions/API_Request_Authorize_3D.php',
                'genesis\\genesis_builder_xml' => '/builders/Genesis_Builder_XML.php',
                'genesis\\genesis_configuration' => '/Genesis_Configuration.php',
                'genesis\\genesis_exception_invalid_ssl_certificate_authority' => '/exceptions/Genesis_Exception_Invalid_SSL_Certificate_Authority.php',
                'genesis\\genesis_exception_required_fields_are_empty' => '/exceptions/Genesis_Exception_Required_Fields_Are_Empty.php',
                'genesis\\genesis_Exception_Invalid_Method' => '/exceptions/Genesis_Exception_Invalid_Method.php',
                'genesis\\genesis_http_request' => '/Genesis_HTTP_Request.php',
                'genesis\\genesis_http_request_curl' => '/http/Genesis_HTTP_Request_cURL.php',
                'genesis\\genesis_api_request_interface' => '/Genesis_API_Request_Interface.php',
                'genesis\\genesis_api_request_base' => '/Genesis_API_Request_Base.php',
                'genesis\\genesis_request_builder' => '/Genesis_Request_Builder.php',
                'genesis\\api_request_blacklist' => '/requests/API_Request_Blacklist.php',
                'genesis\\genesis_base' => '/Genesis_Base.php',
                'genesis\\genesis_errors' => '/Genesis_Errors.php',
                'genesis\\genesis_api_request' => '/Genesis_API_Request.php',
                'initrecurringsale' => '/requests/transactions/API_Request_Init_Recurring_Sale.php',
                'initrecurringsale3d' => '/requests/transactions/API_Request_Init_Recurring_Sale_3D.php',
                'genesis\\api_request_account_verification' => '/requests/transactions/API_Request_Account_Verification.php',
                'genesis\\api_request_avs' => '/requests/transactions/API_Request_AVS.php',
                'reconcile_date_range' => '/requests/reconcile/API_Request_Reconcile_By_Date_Range.php',
                'recurringsale' => '/requests/transactions/API_Request_Recurring_Sale.php',
                'sale3d' => '/requests/transactions/API_Request_Sale_3D.php',
                'singletransaction' => '/requests/reconcile/API_Request_Reconcile_By_Transaction.php',
                'tranasction_capture' => '/requests/transactions/API_Request_Capture.php',
                'genesis\\api_request_authorize' => '/requests/transactions/API_Request_Authorize.php',
                'transaction_credit' => '/requests/transactions/API_Request_Credit.php',
                'transaction_payout' => '/requests/transactions/API_Request_Payout.php',
                'transaction_refund' => '/requests/transactions/API_Request_Refund.php',
                'transaction_sale' => '/requests/transactions/API_Request_Sale.php',
                'genesis\\api_request_void' => '/requests/transactions/API_Request_Void.php',
                'genesis\\api_request_notification_echo' => '/requests/API_Request_Notification_Echo.php',
                'genesis\\api_request_wpf_create' => '/requests/wpf/API_Request_WPF_Create.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd

define('ROOT_PATH', dirname(__FILE__));